{{- if .Values.externalSecrets.enabled }}
{{- $namespaces := list "aip-text" "aip-multimodal" "aip-video" }}
{{- range $ns := $namespaces }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aip-common-secrets
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: aip-common-secrets
    creationPolicy: Owner
  data:
    - secretKey: mongo-uri
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteKey | quote }}
        property: mongo-uri
    - secretKey: redis-uri
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteKey | quote }}
        property: redis-uri
    - secretKey: rabbitmq-uri
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteKey | quote }}
        property: rabbitmq-uri
{{- end }}
{{- end }}
