{{- $namespaces := list "aip-text" "aip-multimodal" "aip-video" }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aip-common-secrets
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: aip-common-secrets
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
type: Opaque
stringData:
  mongo-uri: {{ $.Values.commonSecrets.mongoUri | default "mongodb://aip_root:aip_mongo_secure_password_prod@mongodb.aip-infra.svc.cluster.local:27017/ai_platform?authSource=admin" | quote }}
  redis-uri: {{ $.Values.commonSecrets.redisUri | default "redis://:aip_redis_secure_password_prod@redis.aip-infra.svc.cluster.local:6379/0" | quote }}
  rabbitmq-uri: {{ $.Values.commonSecrets.rabbitmqUri | default "amqp://aip:aip_rabbitmq_secure_password_prod@rabbitmq.aip-infra.svc.cluster.local:5672/aip" | quote }}
{{- end }}
