{{- if and .Values.externalSecrets.enabled (not .Values.existingSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "aip-control.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.jwtSecret | quote }}
        property: jwt-secret
    - secretKey: master-pepper
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.masterPepper | quote }}
        property: master-pepper
{{- end }}
