{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "aip-control.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | default "aip-default-jwt-secret-change-in-production-min32" | b64enc | quote }}
  master-pepper: {{ .Values.secrets.masterPepper | default "aip-default-master-pepper-change-in-production-min32" | b64enc | quote }}
{{- end }}
