
from fastapi import APIRouter, Request
from pydantic import BaseModel, Field

router = APIRouter(prefix="/v1", tags=["Completions"])


class CompletionRequest(BaseModel):
    model: str = Field(..., json_schema_extra={"example": "chat-general-standard"})
    prompt: str | list[str] = Field(..., json_schema_extra={"example": "Once upon a time in AI Platform,"})
    max_tokens: int | None = Field(64, ge=1)
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    stream: bool = Field(False, json_schema_extra={"example": False})


@router.post("/completions")
async def create_completion(
    request: Request,
    payload: CompletionRequest,
):
    return {
        "id": "cmpl-01HXEXAMPLE",
        "object": "text_completion",
        "created": 1770970000,
        "model": payload.model,
        "choices": [
            {
                "text": " a legacy completion response was generated by AI Inference Platform.",
                "index": 0,
                "logprobs": None,
                "finish_reason": "length"
            }
        ],
        "usage": {
            "prompt_tokens": 8,
            "completion_tokens": 12,
            "total_tokens": 20
        }
    }
