
import time
from fastapi import APIRouter, Request, Response
from pydantic import BaseModel, Field
from src.cache.inference_cache import inference_cache

router = APIRouter(prefix="/v1", tags=["Completions"])


class CompletionRequest(BaseModel):
    model: str = Field(..., json_schema_extra={"example": "chat-general-standard"})
    prompt: str | list[str] = Field(..., json_schema_extra={"example": "Once upon a time in AI Platform,"})
    max_tokens: int | None = Field(64, ge=1)
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    stream: bool = Field(False, json_schema_extra={"example": False})


@router.post("/completions")
async def create_completion(
    request: Request,
    payload: CompletionRequest,
    response: Response,
):
    start_time = time.time()
    eligible_for_cache = not payload.stream and (payload.temperature == 0.0 or request.headers.get("X-AIP-Cache", "").lower() == "true")
    if eligible_for_cache:
        cached_val, is_hit = await inference_cache.get(
            domain="completions",
            model_or_alias=payload.model,
            payload_data=payload.model_dump(),
            request=request,
        )
        if is_hit and cached_val:
            if response:
                inference_cache.inject_headers(response, is_hit=True, duration_ms=(time.time() - start_time) * 1000)
            return cached_val

    resp_obj = {
        "id": "cmpl-01HXEXAMPLE",
        "object": "text_completion",
        "created": int(time.time()),
        "model": payload.model,
        "choices": [
            {
                "text": " a legacy completion response was generated by AI Inference Platform.",
                "index": 0,
                "logprobs": None,
                "finish_reason": "length"
            }
        ],
        "usage": {
            "prompt_tokens": 8,
            "completion_tokens": 12,
            "total_tokens": 20
        }
    }

    if eligible_for_cache:
        await inference_cache.set(
            domain="completions",
            model_or_alias=payload.model,
            payload_data=payload.model_dump(),
            response_data=resp_obj,
            ttl_seconds=3600,
        )
        if response:
            inference_cache.inject_headers(response, is_hit=False, duration_ms=(time.time() - start_time) * 1000)

    return resp_obj

