{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aip-mongodb-secret
  namespace: aip-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: aip-mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.mongodb | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.mongodb | quote }}
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aip-redis-secret
  namespace: aip-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: aip-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.redis | quote }}
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aip-rabbitmq-secret
  namespace: aip-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: aip-rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.rabbitmq | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.rabbitmq | quote }}
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aip-minio-secret
  namespace: aip-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: aip-minio-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.minio | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.minio | quote }}
        property: password
{{- end }}
